# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/p8101/Desktop/school/Univ/Special_project/LeNet_5_Eyeriss_v2/sim/PYNQ_Z2/PYNQ_Z2.srcs/sources_1/ip/ROM_sparse_weight/ROM_sparse_weight.xci
# IP: The module: 'ROM_sparse_weight' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/p8101/Desktop/school/Univ/Special_project/LeNet_5_Eyeriss_v2/sim/PYNQ_Z2/PYNQ_Z2.srcs/sources_1/ip/ROM_sparse_weight/ROM_sparse_weight_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ROM_sparse_weight'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/Users/p8101/Desktop/school/Univ/Special_project/LeNet_5_Eyeriss_v2/sim/PYNQ_Z2/PYNQ_Z2.srcs/sources_1/ip/ROM_sparse_weight/ROM_sparse_weight.xci
# IP: The module: 'ROM_sparse_weight' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/p8101/Desktop/school/Univ/Special_project/LeNet_5_Eyeriss_v2/sim/PYNQ_Z2/PYNQ_Z2.srcs/sources_1/ip/ROM_sparse_weight/ROM_sparse_weight_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ROM_sparse_weight'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
