# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Users/p8101/Desktop/school/Univ/Special_project/LeNet_5_Eyeriss_v2/src/constraints/constraints.xdc

# IP: ip/IP_ifmap_BRAM/IP_ifmap_BRAM.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==IP_ifmap_BRAM || ORIG_REF_NAME==IP_ifmap_BRAM} -quiet] -quiet

# IP: ip/IP_Psum_Rearrange_BRAM/IP_Psum_Rearrange_BRAM.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==IP_Psum_Rearrange_BRAM || ORIG_REF_NAME==IP_Psum_Rearrange_BRAM} -quiet] -quiet

# IP: ip/IP_Psum_Data_SRAM_BRAM/IP_Psum_Data_SRAM_BRAM.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==IP_Psum_Data_SRAM_BRAM || ORIG_REF_NAME==IP_Psum_Data_SRAM_BRAM} -quiet] -quiet

# IP: ip/IP_Iact_Data_SRAM_BRAM/IP_Iact_Data_SRAM_BRAM.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==IP_Iact_Data_SRAM_BRAM || ORIG_REF_NAME==IP_Iact_Data_SRAM_BRAM} -quiet] -quiet

# IP: ip/IP_Iact_Addr_SRAM_BRAM/IP_Iact_Addr_SRAM_BRAM.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==IP_Iact_Addr_SRAM_BRAM || ORIG_REF_NAME==IP_Iact_Addr_SRAM_BRAM} -quiet] -quiet

# IP: ip/IP_Weight_DATA_Spad_BRAM/IP_Weight_DATA_Spad_BRAM.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==IP_Weight_DATA_Spad_BRAM || ORIG_REF_NAME==IP_Weight_DATA_Spad_BRAM} -quiet] -quiet

# IP: ip/IP_Iact_DATA_Spad_BRAM/IP_Iact_DATA_Spad_BRAM.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==IP_Iact_DATA_Spad_BRAM || ORIG_REF_NAME==IP_Iact_DATA_Spad_BRAM} -quiet] -quiet

# IP: ip/IP_Psum_DATA_Spad_BRAM/IP_Psum_DATA_Spad_BRAM.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==IP_Psum_DATA_Spad_BRAM || ORIG_REF_NAME==IP_Psum_DATA_Spad_BRAM} -quiet] -quiet
