# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/p8101/Desktop/school/Univ/Special_project/LeNet_5_Eyeriss_v2/sim/PYNQ_Z2/PYNQ_Z2.srcs/sources_1/ip/processing_system7_0/processing_system7_0.xci
# IP: The module: 'processing_system7_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/p8101/Desktop/school/Univ/Special_project/LeNet_5_Eyeriss_v2/sim/PYNQ_Z2/PYNQ_Z2.srcs/sources_1/ip/processing_system7_0/processing_system7_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'processing_system7_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: c:/Users/p8101/Desktop/school/Univ/Special_project/LeNet_5_Eyeriss_v2/sim/PYNQ_Z2/PYNQ_Z2.srcs/sources_1/ip/processing_system7_0/processing_system7_0.xci
# IP: The module: 'processing_system7_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/p8101/Desktop/school/Univ/Special_project/LeNet_5_Eyeriss_v2/sim/PYNQ_Z2/PYNQ_Z2.srcs/sources_1/ip/processing_system7_0/processing_system7_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'processing_system7_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
